In [4]:
#import required libraries
import pandas as pd

In [6]:
#read the processed dataset
df=pd.read_csv('processedData1.csv')
df

,gT,sId,rId,sAcc,rAcc,TranAmount,TranType,TranStatus,sBalbefore,sBalAfter,rBalBefore,rBalAfter,sf1,sf2,sTD,rTD,TranTS,sType,rType
0,N-RegDep,PN_Ret2,PN_EU_0_261,RAcc2,EUAcc0_261,131926.49,Dt,SU,1.000000e+09,9.998681e+08,1.001319e+08,1.000000e+08,True,True,1/6/2011 0:11:22,1/6/2011 0:11:22,1/6/2011 0:11:22,RET,EU
1,N_Reg_RC,PN_EU_1_502,operator,EUAcc1_502,A0,2054.46,ArRC,SU,1.000000e+08,9.999795e+07,9.918004e+07,9.917798e+07,True,True,1/6/2011 0:16:8,1/6/2011 0:16:8,1/6/2011 0:16:8,EU,operator
2,N-RegDep,PN_Ret2,PN_EU_1_362,RAcc2,EUAcc1_362,182548.74,Dt,SU,9.998681e+08,9.996855e+08,1.001825e+08,1.000000e+08,True,True,1/6/2011 0:36:47,1/6/2011 0:36:47,1/6/2011 0:36:47,RET,EU
3,N_Reg_RC,PN_EU_1_26,operator,EUAcc1_26,A0,5507.28,ArRC,SU,1.000000e+08,9.999449e+07,9.918554e+07,9.918004e+07,True,True,1/6/2011 0:36:59,1/6/2011 0:36:59,1/6/2011 0:36:59,EU,operator
4,N_Reg_RC,PN_EU_1_18,operator,EUAcc1_18,A0,2102.60,ArRC,SU,1.000000e+08,9.999790e+07,9.918765e+07,9.918554e+07,True,True,1/6/2011 1:1:26,1/6/2011 1:1:26,1/6/2011 1:1:26,EU,operator
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54217,N_Reg_RC,PN_EU_0_116,operator,EUAcc0_116,A0,524.70,ArRC,SU,9.999828e+07,9.999775e+07,1.886426e+08,1.886421e+08,True,True,30/9/2011 23:30:0,30/9/2011 23:30:0,30/9/2011 23:30:0,EU,operator
54218,N_Reg_RC,PN_EU_0_1256,operator,EUAcc0_1256,A0,2106.86,ArRC,SU,9.998486e+07,9.998276e+07,1.886448e+08,1.886426e+08,True,True,30/9/2011 23:32:19,30/9/2011 23:32:19,30/9/2011 23:32:19,EU,operator
54219,N-RegDep,PN_Ret6,PN_EU_1_143,RAcc6,EUAcc1_143,213240.93,Dt,SU,8.785127e+08,8.782994e+08,1.008969e+08,1.006837e+08,True,True,30/9/2011 23:33:23,30/9/2011 23:33:23,30/9/2011 23:33:23,RET,EU
54220,N-RegC2C,PN_EU_1_197,PN_EU_2_85,EUAcc1_197,EUAcc2_85,199431.78,Ind,SU,9.755577e+07,9.735435e+07,1.021736e+08,1.019741e+08,True,True,30/9/2011 23:38:5,30/9/2011 23:38:5,30/9/2011 23:38:5,EU,EU
54221,N-RegDep,PN_Ret5,PN_EU_1_360,RAcc5,EUAcc1_360,87364.76,Dt,SU,9.066821e+08,9.065947e+08,1.003316e+08,1.002442e+08,True,True,30/9/2011 23:49:1,30/9/2011 23:49:1,30/9/2011 23:49:1,RET,EU